### ISSUE TITLE
Custom OpenGL renderer

### ISSUE THREAD

**Issue by mdrxy** [WBOR-91-1-FM/wbor-studio-dashboard#15]
May be more performant. Tricky parts would be text rendering, and keeping everything safe. Perhaps Vulkan?

**Comment by CaspianA1** [comment]
I think the current renderer is probably performant enough - just thought about doing it for fun, and to get 3D themes going. Although raw OpenGL would be global state hell, and Vulkan would be a lot, lot, lot of code to write. And doing either would mean making a custom text renderer, which would be a very, very difficult task. Text rendering is a scary thing.

Sticking with SDL's renderer for now is probably the best option. 3D would allow for incredible themes (#32), but that would mean migrating away from SDL's renderer, which is strictly 2D (and probably will always be).

**Comment by CaspianA1** [comment]
There might be some text rendering library that could hook into OpenGL or Vulkan, which might be viable - like Slug, for example - so some work might be avoidable there - but integrating it to handle all the Unicode trickery might still be tricky
