### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by mdrxy** [WBOR-91-1-FM/wbor-studio-dashboard#7]
When an error happens, make it print a message on screen that says that they should reach out to the station email address and ask for the tech director. Also, make a log of the error on the disk. In the future, could send errors to our central admin dashboard.

**Comment by CaspianA1** [comment]
It's printed to stdout/stderr, which is sufficient, I think - it could easily be piped to an output log file in the future if needed. Also, most of the problems encountered are network errors (which would be fixed if Ethernet could be used).

**Comment by mdrxy** [comment]
I think we'll get it on Ethernet in the new station due to a higher port allowance
